# Generated by Django 3.2.9 on 2021-11-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellrecord', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellrecord',
            old_name='Purchased_items',
            new_name='purchased_items',
        ),
    ]
